# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1267, 672)
        MainWindow.setStyleSheet("QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffa02f;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #404040;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
"}\n"
"\n"
"QWidget:focus\n"
"{\n"
"    /*border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);*/\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #ffaa00;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:/down_arrow.png);\n"
"}\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/images/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(:/images/checkbox.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(220, 10, 1041, 621))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_7.setGeometry(QtCore.QRect(410, 100, 361, 51))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_8.setGeometry(QtCore.QRect(410, 170, 361, 51))
        self.lineEdit_8.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_9.setGeometry(QtCore.QRect(410, 240, 361, 51))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_13 = QtWidgets.QLabel(self.tab_12)
        self.label_13.setGeometry(QtCore.QRect(240, 110, 141, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_12)
        self.label_14.setGeometry(QtCore.QRect(240, 250, 141, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_12)
        self.label_15.setGeometry(QtCore.QRect(240, 180, 141, 31))
        self.label_15.setObjectName("label_15")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_8.setGeometry(QtCore.QRect(70, 430, 921, 61))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton_43 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_43.setGeometry(QtCore.QRect(560, 10, 301, 41))
        self.pushButton_43.setObjectName("pushButton_43")
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setGeometry(QtCore.QRect(70, 10, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.pushButton_38 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_38.setGeometry(QtCore.QRect(350, 330, 261, 61))
        self.pushButton_38.setObjectName("pushButton_38")
        self.tabWidget.addTab(self.tab_12, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.label_17 = QtWidgets.QLabel(self.tab_11)
        self.label_17.setGeometry(QtCore.QRect(220, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_10.setGeometry(QtCore.QRect(380, 170, 441, 41))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 360, 1001, 61))
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.pushButton_44 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_44.setGeometry(QtCore.QRect(760, 10, 231, 41))
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_45.setGeometry(QtCore.QRect(520, 10, 231, 41))
        self.pushButton_45.setObjectName("pushButton_45")
        self.label_18 = QtWidgets.QLabel(self.groupBox_10)
        self.label_18.setGeometry(QtCore.QRect(160, 20, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.pushButton_46 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_46.setGeometry(QtCore.QRect(380, 250, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setObjectName("pushButton_46")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(400, 40, 331, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(770, 40, 201, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setObjectName("pushButton_8")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 110, 1011, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 1021, 561))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 20, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_3.setGeometry(QtCore.QRect(450, 20, 331, 51))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_9.setGeometry(QtCore.QRect(800, 20, 201, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/loupe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label = QtWidgets.QLabel(self.tab_8)
        self.label.setGeometry(QtCore.QRect(360, 20, 81, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 100, 1001, 361))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_14.setGeometry(QtCore.QRect(580, 470, 201, 51))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_15.setGeometry(QtCore.QRect(800, 470, 201, 51))
        self.pushButton_15.setObjectName("pushButton_15")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.textEdit = QtWidgets.QTextEdit(self.tab_9)
        self.textEdit.setGeometry(QtCore.QRect(10, 110, 551, 361))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 30, 551, 51))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_4.setGeometry(QtCore.QRect(670, 30, 331, 51))
        self.comboBox_4.setObjectName("comboBox_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_5.setGeometry(QtCore.QRect(670, 100, 331, 51))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_2 = QtWidgets.QLabel(self.tab_9)
        self.label_2.setGeometry(QtCore.QRect(570, 30, 81, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_9)
        self.label_3.setGeometry(QtCore.QRect(570, 100, 81, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_9)
        self.label_4.setGeometry(QtCore.QRect(570, 170, 81, 41))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_6.setGeometry(QtCore.QRect(670, 170, 331, 51))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_7.setGeometry(QtCore.QRect(670, 230, 331, 51))
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_9 = QtWidgets.QLabel(self.tab_9)
        self.label_9.setGeometry(QtCore.QRect(570, 240, 81, 41))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_9)
        self.label_10.setGeometry(QtCore.QRect(570, 310, 81, 41))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_8.setGeometry(QtCore.QRect(670, 300, 331, 51))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_9.setGeometry(QtCore.QRect(670, 360, 331, 51))
        self.comboBox_9.setObjectName("comboBox_9")
        self.label_11 = QtWidgets.QLabel(self.tab_9)
        self.label_11.setGeometry(QtCore.QRect(570, 370, 81, 41))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_9)
        self.label_12.setGeometry(QtCore.QRect(580, 420, 81, 41))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_11.setGeometry(QtCore.QRect(670, 420, 331, 51))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_17.setGeometry(QtCore.QRect(380, 480, 321, 41))
        self.pushButton_17.setIcon(icon)
        self.pushButton_17.setObjectName("pushButton_17")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.comboBox_15 = QtWidgets.QComboBox(self.tab_21)
        self.comboBox_15.setGeometry(QtCore.QRect(670, 350, 331, 51))
        self.comboBox_15.setObjectName("comboBox_15")
        self.label_21 = QtWidgets.QLabel(self.tab_21)
        self.label_21.setGeometry(QtCore.QRect(570, 360, 81, 41))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_21)
        self.label_22.setGeometry(QtCore.QRect(570, 230, 81, 41))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.comboBox_16 = QtWidgets.QComboBox(self.tab_21)
        self.comboBox_16.setGeometry(QtCore.QRect(670, 290, 331, 51))
        self.comboBox_16.setObjectName("comboBox_16")
        self.label_23 = QtWidgets.QLabel(self.tab_21)
        self.label_23.setGeometry(QtCore.QRect(580, 410, 81, 41))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_21)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 140, 551, 321))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_24 = QtWidgets.QLabel(self.tab_21)
        self.label_24.setGeometry(QtCore.QRect(20, 20, 81, 41))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.comboBox_17 = QtWidgets.QComboBox(self.tab_21)
        self.comboBox_17.setGeometry(QtCore.QRect(670, 220, 331, 51))
        self.comboBox_17.setObjectName("comboBox_17")
        self.label_25 = QtWidgets.QLabel(self.tab_21)
        self.label_25.setGeometry(QtCore.QRect(570, 160, 81, 41))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.comboBox_18 = QtWidgets.QComboBox(self.tab_21)
        self.comboBox_18.setGeometry(QtCore.QRect(670, 90, 331, 51))
        self.comboBox_18.setObjectName("comboBox_18")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_21)
        self.lineEdit_17.setGeometry(QtCore.QRect(670, 410, 331, 51))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_21)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 80, 551, 51))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_21)
        self.lineEdit_19.setGeometry(QtCore.QRect(110, 20, 641, 41))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_21)
        self.lineEdit_20.setGeometry(QtCore.QRect(670, 160, 331, 51))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_26 = QtWidgets.QLabel(self.tab_21)
        self.label_26.setGeometry(QtCore.QRect(570, 300, 81, 41))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_21)
        self.label_27.setGeometry(QtCore.QRect(570, 90, 81, 41))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_21)
        self.pushButton_18.setGeometry(QtCore.QRect(770, 20, 201, 41))
        self.pushButton_18.setIcon(icon1)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_21)
        self.pushButton_19.setGeometry(QtCore.QRect(600, 480, 321, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_19.setIcon(icon2)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_21)
        self.pushButton_20.setGeometry(QtCore.QRect(170, 480, 321, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/x-mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_20.setIcon(icon3)
        self.pushButton_20.setObjectName("pushButton_20")
        self.tabWidget_2.addTab(self.tab_21, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 10, 1021, 561))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_25 = QtWidgets.QWidget()
        self.tab_25.setObjectName("tab_25")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_25)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 10, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_25)
        self.pushButton_12.setGeometry(QtCore.QRect(800, 10, 201, 51))
        self.pushButton_12.setIcon(icon1)
        self.pushButton_12.setObjectName("pushButton_12")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_25)
        self.tableWidget_6.setGeometry(QtCore.QRect(10, 90, 1001, 371))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(4)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        self.comboBox_20 = QtWidgets.QComboBox(self.tab_25)
        self.comboBox_20.setGeometry(QtCore.QRect(380, 10, 331, 51))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_25)
        self.pushButton_16.setGeometry(QtCore.QRect(810, 470, 201, 51))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_30 = QtWidgets.QPushButton(self.tab_25)
        self.pushButton_30.setGeometry(QtCore.QRect(590, 470, 201, 51))
        self.pushButton_30.setObjectName("pushButton_30")
        self.tabWidget_3.addTab(self.tab_25, "")
        self.tab_26 = QtWidgets.QWidget()
        self.tab_26.setObjectName("tab_26")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_26)
        self.lineEdit_22.setGeometry(QtCore.QRect(500, 160, 331, 51))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_26)
        self.lineEdit_23.setGeometry(QtCore.QRect(500, 100, 331, 51))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_26)
        self.lineEdit_24.setGeometry(QtCore.QRect(500, 230, 331, 51))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_26)
        self.lineEdit_25.setGeometry(QtCore.QRect(500, 290, 331, 51))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_26)
        self.pushButton_21.setGeometry(QtCore.QRect(360, 390, 321, 41))
        self.pushButton_21.setIcon(icon)
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_28 = QtWidgets.QLabel(self.tab_26)
        self.label_28.setGeometry(QtCore.QRect(270, 100, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_26)
        self.label_29.setGeometry(QtCore.QRect(270, 230, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_26)
        self.label_30.setGeometry(QtCore.QRect(270, 160, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_26)
        self.label_31.setGeometry(QtCore.QRect(250, 300, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.tabWidget_3.addTab(self.tab_26, "")
        self.tab_27 = QtWidgets.QWidget()
        self.tab_27.setObjectName("tab_27")
        self.label_32 = QtWidgets.QLabel(self.tab_27)
        self.label_32.setGeometry(QtCore.QRect(260, 280, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab_27)
        self.lineEdit_26.setGeometry(QtCore.QRect(490, 340, 331, 51))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_33 = QtWidgets.QLabel(self.tab_27)
        self.label_33.setGeometry(QtCore.QRect(260, 150, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab_27)
        self.lineEdit_27.setGeometry(QtCore.QRect(490, 210, 331, 51))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_27)
        self.lineEdit_28.setGeometry(QtCore.QRect(490, 150, 331, 51))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_27)
        self.lineEdit_29.setGeometry(QtCore.QRect(490, 280, 331, 51))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_34 = QtWidgets.QLabel(self.tab_27)
        self.label_34.setGeometry(QtCore.QRect(270, 210, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_27)
        self.label_35.setGeometry(QtCore.QRect(240, 350, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_27)
        self.pushButton_22.setGeometry(QtCore.QRect(550, 440, 321, 41))
        self.pushButton_22.setIcon(icon)
        self.pushButton_22.setObjectName("pushButton_22")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab_27)
        self.lineEdit_30.setGeometry(QtCore.QRect(50, 40, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.comboBox_19 = QtWidgets.QComboBox(self.tab_27)
        self.comboBox_19.setGeometry(QtCore.QRect(430, 40, 331, 51))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_27)
        self.pushButton_23.setGeometry(QtCore.QRect(800, 40, 201, 51))
        self.pushButton_23.setIcon(icon1)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_27)
        self.pushButton_24.setGeometry(QtCore.QRect(120, 440, 321, 41))
        self.pushButton_24.setIcon(icon3)
        self.pushButton_24.setObjectName("pushButton_24")
        self.tabWidget_3.addTab(self.tab_27, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_7.setGeometry(QtCore.QRect(10, 90, 1021, 431))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(0)
        self.tableWidget_7.setRowCount(0)
        self.pushButton_33 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_33.setGeometry(QtCore.QRect(830, 20, 201, 51))
        self.pushButton_33.setIcon(icon1)
        self.pushButton_33.setObjectName("pushButton_33")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_42.setGeometry(QtCore.QRect(10, 30, 251, 41))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.comboBox_22 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_22.setGeometry(QtCore.QRect(350, 30, 101, 31))
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_23 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_23.setGeometry(QtCore.QRect(530, 30, 101, 31))
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_24 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_24.setGeometry(QtCore.QRect(710, 30, 101, 31))
        self.comboBox_24.setObjectName("comboBox_24")
        self.label_37 = QtWidgets.QLabel(self.tab_5)
        self.label_37.setGeometry(QtCore.QRect(260, 30, 81, 41))
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_5)
        self.label_38.setGeometry(QtCore.QRect(450, 30, 81, 41))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_5)
        self.label_39.setGeometry(QtCore.QRect(630, 30, 81, 41))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.pushButton_31 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_31.setGeometry(QtCore.QRect(830, 530, 201, 51))
        self.pushButton_31.setObjectName("pushButton_31")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_6)
        self.tabWidget_6.setGeometry(QtCore.QRect(10, 10, 1011, 501))
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_30 = QtWidgets.QWidget()
        self.tab_30.setObjectName("tab_30")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab_30)
        self.tableWidget_8.setGeometry(QtCore.QRect(10, 90, 981, 441))
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(6)
        self.tableWidget_8.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(5, item)
        self.dateEdit = QtWidgets.QDateEdit(self.tab_30)
        self.dateEdit.setGeometry(QtCore.QRect(60, 30, 191, 41))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_30)
        self.dateEdit_2.setGeometry(QtCore.QRect(300, 30, 191, 41))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.pushButton_34 = QtWidgets.QPushButton(self.tab_30)
        self.pushButton_34.setGeometry(QtCore.QRect(770, 20, 201, 51))
        self.pushButton_34.setIcon(icon1)
        self.pushButton_34.setObjectName("pushButton_34")
        self.label_40 = QtWidgets.QLabel(self.tab_30)
        self.label_40.setGeometry(QtCore.QRect(10, 30, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_30)
        self.label_41.setGeometry(QtCore.QRect(270, 30, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.tab_30)
        self.lineEdit_50.setGeometry(QtCore.QRect(600, 30, 151, 41))
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.label_42 = QtWidgets.QLabel(self.tab_30)
        self.label_42.setGeometry(QtCore.QRect(520, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.tabWidget_6.addTab(self.tab_30, "")
        self.tab_31 = QtWidgets.QWidget()
        self.tab_31.setObjectName("tab_31")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.tab_31)
        self.dateEdit_3.setGeometry(QtCore.QRect(310, 30, 191, 41))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.pushButton_35 = QtWidgets.QPushButton(self.tab_31)
        self.pushButton_35.setGeometry(QtCore.QRect(770, 20, 201, 51))
        self.pushButton_35.setIcon(icon1)
        self.pushButton_35.setObjectName("pushButton_35")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.tab_31)
        self.tableWidget_9.setGeometry(QtCore.QRect(10, 90, 981, 441))
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(6)
        self.tableWidget_9.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(5, item)
        self.label_43 = QtWidgets.QLabel(self.tab_31)
        self.label_43.setGeometry(QtCore.QRect(520, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_31)
        self.label_44.setGeometry(QtCore.QRect(10, 30, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.dateEdit_4 = QtWidgets.QDateEdit(self.tab_31)
        self.dateEdit_4.setGeometry(QtCore.QRect(60, 30, 191, 41))
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.tab_31)
        self.lineEdit_51.setGeometry(QtCore.QRect(600, 30, 151, 41))
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.label_56 = QtWidgets.QLabel(self.tab_31)
        self.label_56.setGeometry(QtCore.QRect(270, 30, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.tabWidget_6.addTab(self.tab_31, "")
        self.tab_32 = QtWidgets.QWidget()
        self.tab_32.setObjectName("tab_32")
        self.tableWidget_10 = QtWidgets.QTableWidget(self.tab_32)
        self.tableWidget_10.setGeometry(QtCore.QRect(10, 100, 981, 421))
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(0)
        self.tableWidget_10.setRowCount(0)
        self.label_45 = QtWidgets.QLabel(self.tab_32)
        self.label_45.setGeometry(QtCore.QRect(30, 30, 41, 31))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.tab_32)
        self.label_46.setGeometry(QtCore.QRect(320, 30, 51, 31))
        self.label_46.setObjectName("label_46")
        self.comboBox_25 = QtWidgets.QComboBox(self.tab_32)
        self.comboBox_25.setGeometry(QtCore.QRect(90, 30, 181, 41))
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_26 = QtWidgets.QComboBox(self.tab_32)
        self.comboBox_26.setGeometry(QtCore.QRect(400, 30, 181, 41))
        self.comboBox_26.setObjectName("comboBox_26")
        self.pushButton_36 = QtWidgets.QPushButton(self.tab_32)
        self.pushButton_36.setGeometry(QtCore.QRect(740, 30, 201, 41))
        self.pushButton_36.setIcon(icon1)
        self.pushButton_36.setObjectName("pushButton_36")
        self.tabWidget_6.addTab(self.tab_32, "")
        self.pushButton_42 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_42.setGeometry(QtCore.QRect(810, 520, 201, 51))
        self.pushButton_42.setObjectName("pushButton_42")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_7)
        self.tabWidget_5.setGeometry(QtCore.QRect(10, 10, 1021, 561))
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_28 = QtWidgets.QWidget()
        self.tab_28.setObjectName("tab_28")
        self.groupBox = QtWidgets.QGroupBox(self.tab_28)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1001, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_31.setGeometry(QtCore.QRect(10, 40, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_31.setFont(font)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_32.setGeometry(QtCore.QRect(270, 40, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_32.setFont(font)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_33.setGeometry(QtCore.QRect(530, 40, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_25.setGeometry(QtCore.QRect(790, 40, 201, 51))
        self.pushButton_25.setIcon(icon)
        self.pushButton_25.setObjectName("pushButton_25")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 1001, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_34.setGeometry(QtCore.QRect(10, 40, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_34.setFont(font)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_35.setGeometry(QtCore.QRect(270, 40, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_35.setFont(font)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_36.setGeometry(QtCore.QRect(530, 40, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_36.setFont(font)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_26.setGeometry(QtCore.QRect(790, 40, 201, 51))
        self.pushButton_26.setIcon(icon)
        self.pushButton_26.setObjectName("pushButton_26")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 1001, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_37.setGeometry(QtCore.QRect(10, 40, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_37.setFont(font)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_38.setGeometry(QtCore.QRect(270, 40, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_38.setFont(font)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_39.setGeometry(QtCore.QRect(530, 40, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_39.setFont(font)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_27.setGeometry(QtCore.QRect(790, 40, 201, 51))
        self.pushButton_27.setIcon(icon)
        self.pushButton_27.setObjectName("pushButton_27")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_28)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 140, 1001, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_40.setGeometry(QtCore.QRect(50, 40, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_40.setFont(font)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_41.setGeometry(QtCore.QRect(420, 40, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_41.setFont(font)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_28.setGeometry(QtCore.QRect(790, 30, 201, 51))
        self.pushButton_28.setIcon(icon)
        self.pushButton_28.setObjectName("pushButton_28")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_28)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 250, 1001, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_43.setGeometry(QtCore.QRect(50, 40, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_43.setFont(font)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_44.setGeometry(QtCore.QRect(420, 40, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_44.setFont(font)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_29.setGeometry(QtCore.QRect(790, 40, 201, 51))
        self.pushButton_29.setIcon(icon)
        self.pushButton_29.setObjectName("pushButton_29")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_28)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 390, 1001, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_49.setGeometry(QtCore.QRect(20, 40, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_49.setFont(font)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_32.setGeometry(QtCore.QRect(790, 40, 201, 51))
        self.pushButton_32.setIcon(icon)
        self.pushButton_32.setObjectName("pushButton_32")
        self.comboBox_21 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_21.setGeometry(QtCore.QRect(440, 40, 331, 51))
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.label_36 = QtWidgets.QLabel(self.groupBox_6)
        self.label_36.setGeometry(QtCore.QRect(350, 40, 81, 41))
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.tabWidget_5.addTab(self.tab_28, "")
        self.tab_29 = QtWidgets.QWidget()
        self.tab_29.setObjectName("tab_29")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_29)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 0, 471, 531))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_49 = QtWidgets.QLabel(self.groupBox_7)
        self.label_49.setGeometry(QtCore.QRect(0, 80, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_52.setGeometry(QtCore.QRect(190, 20, 271, 41))
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.lineEdit_54 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_54.setGeometry(QtCore.QRect(190, 190, 271, 41))
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_53.setGeometry(QtCore.QRect(190, 80, 271, 41))
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.label_48 = QtWidgets.QLabel(self.groupBox_7)
        self.label_48.setGeometry(QtCore.QRect(0, 190, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.label_50 = QtWidgets.QLabel(self.groupBox_7)
        self.label_50.setGeometry(QtCore.QRect(0, 250, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.lineEdit_55 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_55.setGeometry(QtCore.QRect(190, 250, 271, 41))
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.label_47 = QtWidgets.QLabel(self.groupBox_7)
        self.label_47.setGeometry(QtCore.QRect(-10, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.lineEdit_56 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_56.setGeometry(QtCore.QRect(190, 360, 271, 41))
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.label_51 = QtWidgets.QLabel(self.groupBox_7)
        self.label_51.setGeometry(QtCore.QRect(-10, 370, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.groupBox_7)
        self.label_52.setGeometry(QtCore.QRect(-10, 430, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.lineEdit_57 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_57.setGeometry(QtCore.QRect(190, 420, 271, 41))
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.pushButton_37 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_37.setGeometry(QtCore.QRect(170, 480, 151, 41))
        self.pushButton_37.setIcon(icon)
        self.pushButton_37.setObjectName("pushButton_37")
        self.label_54 = QtWidgets.QLabel(self.groupBox_7)
        self.label_54.setGeometry(QtCore.QRect(-10, 310, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_58.setGeometry(QtCore.QRect(190, 300, 271, 41))
        self.lineEdit_58.setText("")
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.label_57 = QtWidgets.QLabel(self.groupBox_7)
        self.label_57.setGeometry(QtCore.QRect(10, 140, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_57.setObjectName("label_57")
        self.lineEdit_60 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_60.setGeometry(QtCore.QRect(190, 140, 271, 41))
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_29)
        self.groupBox_9.setGeometry(QtCore.QRect(490, 10, 511, 521))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_59 = QtWidgets.QLabel(self.groupBox_9)
        self.label_59.setGeometry(QtCore.QRect(0, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.lineEdit_65 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_65.setGeometry(QtCore.QRect(200, 220, 271, 41))
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.lineEdit_66 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_66.setGeometry(QtCore.QRect(200, 170, 271, 41))
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.label_60 = QtWidgets.QLabel(self.groupBox_9)
        self.label_60.setGeometry(QtCore.QRect(20, 220, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.groupBox_9)
        self.label_61.setGeometry(QtCore.QRect(10, 320, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.lineEdit_67 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_67.setGeometry(QtCore.QRect(200, 320, 271, 41))
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.lineEdit_68 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_68.setGeometry(QtCore.QRect(200, 420, 271, 41))
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.label_63 = QtWidgets.QLabel(self.groupBox_9)
        self.label_63.setGeometry(QtCore.QRect(10, 420, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_39.setGeometry(QtCore.QRect(180, 470, 151, 41))
        self.pushButton_39.setIcon(icon2)
        self.pushButton_39.setObjectName("pushButton_39")
        self.lineEdit_64 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_64.setGeometry(QtCore.QRect(200, 20, 271, 41))
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.lineEdit_69 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_69.setGeometry(QtCore.QRect(200, 70, 271, 41))
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.label_62 = QtWidgets.QLabel(self.groupBox_9)
        self.label_62.setGeometry(QtCore.QRect(20, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.label_64 = QtWidgets.QLabel(self.groupBox_9)
        self.label_64.setGeometry(QtCore.QRect(-20, 70, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.pushButton_40 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_40.setGeometry(QtCore.QRect(200, 120, 71, 41))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_41.setGeometry(QtCore.QRect(280, 120, 191, 41))
        self.pushButton_41.setObjectName("pushButton_41")
        self.label_55 = QtWidgets.QLabel(self.groupBox_9)
        self.label_55.setGeometry(QtCore.QRect(0, 370, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_59.setGeometry(QtCore.QRect(200, 370, 271, 41))
        self.lineEdit_59.setText("")
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.lineEdit_61 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_61.setGeometry(QtCore.QRect(200, 270, 271, 41))
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.label_58 = QtWidgets.QLabel(self.groupBox_9)
        self.label_58.setGeometry(QtCore.QRect(20, 270, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_58.setObjectName("label_58")
        self.tabWidget_5.addTab(self.tab_29, "")
        self.tab_33 = QtWidgets.QWidget()
        self.tab_33.setObjectName("tab_33")
        self.comboBox_27 = QtWidgets.QComboBox(self.tab_33)
        self.comboBox_27.setGeometry(QtCore.QRect(340, 60, 311, 41))
        self.comboBox_27.setObjectName("comboBox_27")
        self.label_53 = QtWidgets.QLabel(self.tab_33)
        self.label_53.setGeometry(QtCore.QRect(200, 60, 111, 31))
        self.label_53.setObjectName("label_53")
        self.checkBox = QtWidgets.QCheckBox(self.tab_33)
        self.checkBox.setGeometry(QtCore.QRect(50, 160, 81, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_33)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 190, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_33)
        self.checkBox_3.setGeometry(QtCore.QRect(50, 220, 101, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_33)
        self.checkBox_6.setGeometry(QtCore.QRect(50, 310, 111, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_33)
        self.checkBox_5.setGeometry(QtCore.QRect(50, 250, 81, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_33)
        self.checkBox_4.setGeometry(QtCore.QRect(50, 280, 81, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_33)
        self.checkBox_7.setGeometry(QtCore.QRect(350, 190, 81, 20))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_33)
        self.checkBox_8.setGeometry(QtCore.QRect(350, 160, 81, 20))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_33)
        self.checkBox_9.setGeometry(QtCore.QRect(350, 220, 81, 20))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_33)
        self.checkBox_10.setGeometry(QtCore.QRect(350, 280, 81, 20))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab_33)
        self.checkBox_11.setGeometry(QtCore.QRect(350, 250, 81, 20))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab_33)
        self.checkBox_12.setGeometry(QtCore.QRect(350, 310, 81, 20))
        self.checkBox_12.setObjectName("checkBox_12")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_33)
        self.pushButton_10.setGeometry(QtCore.QRect(350, 450, 241, 61))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_33)
        self.pushButton_11.setGeometry(QtCore.QRect(720, 60, 151, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget_5.addTab(self.tab_33, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_13.setGeometry(QtCore.QRect(310, 330, 311, 71))
        self.pushButton_13.setObjectName("pushButton_13")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 80, 311, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.tab_10)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 151, 16))
        self.label_5.setObjectName("label_5")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tab_10)
        self.dateTimeEdit.setGeometry(QtCore.QRect(160, 200, 311, 51))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_6 = QtWidgets.QLabel(self.tab_10)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 111, 21))
        self.label_6.setObjectName("label_6")
        self.dateEdit_5 = QtWidgets.QDateEdit(self.tab_10)
        self.dateEdit_5.setGeometry(QtCore.QRect(160, 140, 311, 51))
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.label_7 = QtWidgets.QLabel(self.tab_10)
        self.label_7.setGeometry(QtCore.QRect(20, 160, 111, 21))
        self.label_7.setObjectName("label_7")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_10)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 270, 311, 41))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_8 = QtWidgets.QLabel(self.tab_10)
        self.label_8.setGeometry(QtCore.QRect(20, 280, 101, 31))
        self.label_8.setObjectName("label_8")
        self.tabWidget_5.addTab(self.tab_10, "")
        self.tabWidget.addTab(self.tab_7, "")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 201, 81))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 100, 201, 81))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/bookmark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 190, 201, 81))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/customer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon6)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 280, 201, 81))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/monitor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon7)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 460, 201, 81))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon8)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 370, 201, 81))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon9)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 550, 201, 81))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon10)
        self.pushButton_7.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1267, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_13.setText(_translate("MainWindow", "UserName"))
        self.label_14.setText(_translate("MainWindow", "Branch"))
        self.label_15.setText(_translate("MainWindow", "Password"))
        self.pushButton_43.setText(_translate("MainWindow", "Reset"))
        self.label_16.setText(_translate("MainWindow", "Your Password Incorrect , reset your Password"))
        self.pushButton_38.setText(_translate("MainWindow", "Login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "Page"))
        self.label_17.setText(_translate("MainWindow", "Enter your mail"))
        self.pushButton_44.setText(_translate("MainWindow", "Login"))
        self.pushButton_45.setText(_translate("MainWindow", "Resend on Gmail"))
        self.label_18.setText(_translate("MainWindow", "Login From Here"))
        self.pushButton_46.setText(_translate("MainWindow", "Send Me on Gmail"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Page"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Book Title"))
        self.comboBox.setItemText(0, _translate("MainWindow", "rent"))
        self.comboBox.setItemText(1, _translate("MainWindow", "retrive"))
        self.pushButton_8.setText(_translate("MainWindow", "Add"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "book-code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "book-name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Client"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "from"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "to"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Book tittle"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "--------------"))
        self.pushButton_9.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Categroy"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "book code"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "book title"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "book categroy"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "book author"))
        self.pushButton_14.setText(_translate("MainWindow", "Import "))
        self.pushButton_15.setText(_translate("MainWindow", "Export"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "All Books"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Book Full Description"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Book title"))
        self.label_2.setText(_translate("MainWindow", "Categroy"))
        self.label_3.setText(_translate("MainWindow", "Price"))
        self.label_4.setText(_translate("MainWindow", "Code"))
        self.label_9.setText(_translate("MainWindow", "Publisher"))
        self.label_10.setText(_translate("MainWindow", "author"))
        self.label_11.setText(_translate("MainWindow", "Status"))
        self.label_12.setText(_translate("MainWindow", "Part order"))
        self.pushButton_17.setText(_translate("MainWindow", "Add"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Add New Books"))
        self.label_21.setText(_translate("MainWindow", "Status"))
        self.label_22.setText(_translate("MainWindow", "Publisher"))
        self.label_23.setText(_translate("MainWindow", "Part order"))
        self.textEdit_4.setPlaceholderText(_translate("MainWindow", "Book Full Description"))
        self.label_24.setText(_translate("MainWindow", "Code"))
        self.label_25.setText(_translate("MainWindow", "Price"))
        self.lineEdit_18.setPlaceholderText(_translate("MainWindow", "Book title"))
        self.label_26.setText(_translate("MainWindow", "author"))
        self.label_27.setText(_translate("MainWindow", "Categroy"))
        self.pushButton_18.setText(_translate("MainWindow", "Search"))
        self.pushButton_19.setText(_translate("MainWindow", "Save Book"))
        self.pushButton_20.setText(_translate("MainWindow", "Delete Books"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_21), _translate("MainWindow", "Edit Or Delete Books"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.lineEdit_21.setPlaceholderText(_translate("MainWindow", "Book tittle"))
        self.pushButton_12.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Client Name"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client Mail"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Client National-id"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Join Date"))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "Client Name"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "Client Mail"))
        self.comboBox_20.setItemText(2, _translate("MainWindow", "Client Phone"))
        self.comboBox_20.setItemText(3, _translate("MainWindow", "Client National-id"))
        self.pushButton_16.setText(_translate("MainWindow", "Export"))
        self.pushButton_30.setText(_translate("MainWindow", "Import "))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_25), _translate("MainWindow", "All Client"))
        self.pushButton_21.setText(_translate("MainWindow", "Add"))
        self.label_28.setText(_translate("MainWindow", "Client Name"))
        self.label_29.setText(_translate("MainWindow", "Client Phone"))
        self.label_30.setText(_translate("MainWindow", "Client Mail"))
        self.label_31.setText(_translate("MainWindow", "Client National-id"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_26), _translate("MainWindow", "Add New Client"))
        self.label_32.setText(_translate("MainWindow", "Client Phone"))
        self.label_33.setText(_translate("MainWindow", "Client Name"))
        self.label_34.setText(_translate("MainWindow", "Client Mail"))
        self.label_35.setText(_translate("MainWindow", "Client National-id"))
        self.pushButton_22.setText(_translate("MainWindow", "Save Client Data"))
        self.lineEdit_30.setPlaceholderText(_translate("MainWindow", "Enter Client Data"))
        self.comboBox_19.setItemText(0, _translate("MainWindow", "Client Name"))
        self.comboBox_19.setItemText(1, _translate("MainWindow", "Client Mail"))
        self.comboBox_19.setItemText(2, _translate("MainWindow", "Client Phone"))
        self.comboBox_19.setItemText(3, _translate("MainWindow", "Client National-id"))
        self.pushButton_23.setText(_translate("MainWindow", "Search"))
        self.pushButton_24.setText(_translate("MainWindow", "Delete Client"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_27), _translate("MainWindow", "Edit Or Delete Client"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.pushButton_33.setText(_translate("MainWindow", "Search"))
        self.lineEdit_42.setPlaceholderText(_translate("MainWindow", "Enter User Name"))
        self.comboBox_22.setItemText(0, _translate("MainWindow", "--------------"))
        self.comboBox_22.setItemText(1, _translate("MainWindow", "Login"))
        self.comboBox_22.setItemText(2, _translate("MainWindow", "Logout"))
        self.comboBox_22.setItemText(3, _translate("MainWindow", "Add Book"))
        self.comboBox_22.setItemText(4, _translate("MainWindow", "Edit Book"))
        self.comboBox_22.setItemText(5, _translate("MainWindow", "Delete Book "))
        self.comboBox_22.setItemText(6, _translate("MainWindow", "Add Client"))
        self.comboBox_22.setItemText(7, _translate("MainWindow", "Edit Client"))
        self.comboBox_22.setItemText(8, _translate("MainWindow", "Delete Client"))
        self.comboBox_22.setItemText(9, _translate("MainWindow", "Add Retrive"))
        self.comboBox_22.setItemText(10, _translate("MainWindow", "Add Rent"))
        self.label_37.setText(_translate("MainWindow", "Action"))
        self.label_38.setText(_translate("MainWindow", "Table"))
        self.label_39.setText(_translate("MainWindow", "Branch"))
        self.pushButton_31.setText(_translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Page"))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Code"))
        item = self.tableWidget_8.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Categroy"))
        item = self.tableWidget_8.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Author"))
        item = self.tableWidget_8.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget_8.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Quantity"))
        self.pushButton_34.setText(_translate("MainWindow", "Search"))
        self.label_40.setText(_translate("MainWindow", "From"))
        self.label_41.setText(_translate("MainWindow", "To"))
        self.label_42.setText(_translate("MainWindow", "Quantity"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_30), _translate("MainWindow", "Book Reports"))
        self.pushButton_35.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Code"))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Categroy"))
        item = self.tableWidget_9.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Author"))
        item = self.tableWidget_9.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget_9.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Books"))
        self.label_43.setText(_translate("MainWindow", "Quantity"))
        self.label_44.setText(_translate("MainWindow", "From"))
        self.label_56.setText(_translate("MainWindow", "To"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_31), _translate("MainWindow", "Client Report"))
        self.label_45.setText(_translate("MainWindow", "Year"))
        self.label_46.setText(_translate("MainWindow", "Montly"))
        self.pushButton_36.setText(_translate("MainWindow", "Search"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_32), _translate("MainWindow", "Monthly Report"))
        self.pushButton_42.setText(_translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Page"))
        self.groupBox.setTitle(_translate("MainWindow", "Add Branch "))
        self.lineEdit_31.setPlaceholderText(_translate("MainWindow", "Branch Name"))
        self.lineEdit_32.setPlaceholderText(_translate("MainWindow", "Branch Code"))
        self.lineEdit_33.setPlaceholderText(_translate("MainWindow", "Branch Location"))
        self.pushButton_25.setText(_translate("MainWindow", "Add Branch"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Add Branch "))
        self.lineEdit_34.setPlaceholderText(_translate("MainWindow", "Branch Name"))
        self.lineEdit_35.setPlaceholderText(_translate("MainWindow", "Branch Code"))
        self.lineEdit_36.setPlaceholderText(_translate("MainWindow", "Branch Location"))
        self.pushButton_26.setText(_translate("MainWindow", "Add Branch"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Add Branch "))
        self.lineEdit_37.setPlaceholderText(_translate("MainWindow", "Branch Name"))
        self.lineEdit_38.setPlaceholderText(_translate("MainWindow", "Branch Code"))
        self.lineEdit_39.setPlaceholderText(_translate("MainWindow", "Branch Location"))
        self.pushButton_27.setText(_translate("MainWindow", "Add Branch"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Add Puplisher"))
        self.lineEdit_40.setPlaceholderText(_translate("MainWindow", "Puplisher Name"))
        self.lineEdit_41.setPlaceholderText(_translate("MainWindow", "Puplisher Location"))
        self.pushButton_28.setText(_translate("MainWindow", "Add Puplisher"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Add Author"))
        self.lineEdit_43.setPlaceholderText(_translate("MainWindow", "Author Name"))
        self.lineEdit_44.setPlaceholderText(_translate("MainWindow", "Author Location"))
        self.pushButton_29.setText(_translate("MainWindow", "Add Author"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Add Categroy"))
        self.lineEdit_49.setPlaceholderText(_translate("MainWindow", "Author Name"))
        self.pushButton_32.setText(_translate("MainWindow", "Add Categroy"))
        self.comboBox_21.setItemText(0, _translate("MainWindow", "------------------"))
        self.label_36.setText(_translate("MainWindow", "Categroy"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_28), _translate("MainWindow", "Add data"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Add Employee"))
        self.label_49.setText(_translate("MainWindow", "Employee Mail"))
        self.label_48.setText(_translate("MainWindow", "Employee Phone"))
        self.label_50.setText(_translate("MainWindow", "Employee National-id"))
        self.label_47.setText(_translate("MainWindow", "Employee Name"))
        self.label_51.setText(_translate("MainWindow", "Password"))
        self.label_52.setText(_translate("MainWindow", "Password Confirm"))
        self.pushButton_37.setText(_translate("MainWindow", "Add Employee"))
        self.label_54.setText(_translate("MainWindow", "Periority"))
        self.label_57.setText(_translate("MainWindow", "Branch"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Edit Employee Information"))
        self.label_59.setText(_translate("MainWindow", "Employee Mail"))
        self.label_60.setText(_translate("MainWindow", "Employee Phone"))
        self.label_61.setText(_translate("MainWindow", "Employee National-id"))
        self.label_63.setText(_translate("MainWindow", "Password"))
        self.pushButton_39.setText(_translate("MainWindow", "Save"))
        self.label_62.setText(_translate("MainWindow", "Employee Name"))
        self.label_64.setText(_translate("MainWindow", "Password "))
        self.pushButton_40.setText(_translate("MainWindow", "Check"))
        self.pushButton_41.setText(_translate("MainWindow", "Forget My Password"))
        self.label_55.setText(_translate("MainWindow", "Periority"))
        self.label_58.setText(_translate("MainWindow", "Branch"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_29), _translate("MainWindow", "Add Employee"))
        self.label_53.setText(_translate("MainWindow", "Employee"))
        self.checkBox.setText(_translate("MainWindow", "Add Book"))
        self.checkBox_2.setText(_translate("MainWindow", "Edit Book"))
        self.checkBox_3.setText(_translate("MainWindow", "Delete Book "))
        self.checkBox_6.setText(_translate("MainWindow", "Delete Client"))
        self.checkBox_5.setText(_translate("MainWindow", "Add Client"))
        self.checkBox_4.setText(_translate("MainWindow", "Edit Client "))
        self.checkBox_7.setText(_translate("MainWindow", "Clients"))
        self.checkBox_8.setText(_translate("MainWindow", "Books"))
        self.checkBox_9.setText(_translate("MainWindow", "Dashbord "))
        self.checkBox_10.setText(_translate("MainWindow", "Reports"))
        self.checkBox_11.setText(_translate("MainWindow", "History"))
        self.checkBox_12.setText(_translate("MainWindow", "Settings"))
        self.pushButton_10.setText(_translate("MainWindow", "Apply"))
        self.pushButton_11.setText(_translate("MainWindow", "Check"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_33), _translate("MainWindow", "Add User Permisions"))
        self.pushButton_13.setText(_translate("MainWindow", "Set Schedule"))
        self.label_5.setText(_translate("MainWindow", "Enter Your Email"))
        self.label_6.setText(_translate("MainWindow", "Set Time"))
        self.label_7.setText(_translate("MainWindow", "Set date"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Daily"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Monthly"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Annually"))
        self.label_8.setText(_translate("MainWindow", "Report Type"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_10), _translate("MainWindow", "Admin Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Page"))
        self.pushButton.setText(_translate("MainWindow", "Today"))
        self.pushButton_2.setText(_translate("MainWindow", "Books"))
        self.pushButton_3.setText(_translate("MainWindow", "Clients"))
        self.pushButton_4.setText(_translate("MainWindow", "Dashbord"))
        self.pushButton_5.setText(_translate("MainWindow", "Reports"))
        self.pushButton_6.setText(_translate("MainWindow", "History"))
        self.pushButton_7.setText(_translate("MainWindow", "Settings"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
